version: '3'

services:
  api:
    volumes:
      - ./api:/app:ro
    build:
      context: ./api
      args:
        NODE_ENV: development
    command: npm run dev
    environment:
      - NODE_ENV=developmet
