version: '3'

services:
  api:
    build:
      context: ./api
      args:
        - NODE_ENV=production
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
    command: node server.js
